# encoding: utf-8
[BeerEstablishment, Establishment, Beer].each &:destroy_all

bulldog      = Establishment.create! name: 'Bulldog Northeast', address: '401 E Hennepin Ave, Minneapolis, MN 55414', url: 'foobar.com'
macs         = Establishment.create! name: "Macs Industrial", address: '312 Central Ave SE  Minneapolis, Minnesota 55414', url: 'foobar.com'
muddy_waters = Establishment.create! name: 'Muddy Waters', address: '2933 Lyndale Ave S  Minneapolis, MN 55408', url: 'foobar.com'
groveland    = Establishment.create! name: 'Groveland Tap', address: '1834 St Clair Ave  St Paul, MN 55105', url: 'foobar.com'
blue_nile    = Establishment.create! name: 'Blue Nile', address: '2027 E Franklin Ave  Minneapolis, MN 55404', url: 'foobar.com'
happy_gnome  = Establishment.create! name: 'Happy Gnome', address: '498 Selby Ave  St Paul, MN 55102', url: 'foobar.com'
muddy_pig    = Establishment.create! name: 'Muddy Pig', address: '162 Dale St N  St Paul, MN 55102', url: 'foobar.com'
stanleys     = Establishment.create! name: "Stanleys Bar Room", address: '2500 University Ave NE  Minneapolis, MN 55418', url: 'foobar.com'

beers = [
  "3rd Street Three Way Pale Ale",
  "Affligem Noël",
  "Alaskan Smoked Porter vintage 2002",
  "Alaskan Smoked Porter vintage 2004",
  "Alaskan Smoked Porter vintage 2008",
  "Alaskan Smoked Porter vintage 2010",
  "Angry Orchard Cider",
  "Aspall Cider",
  "Avery Collaboration not Litigation",
  "Avery Samael’s Oak Aged Ale",
  "Avery Samael’s Oak Aged Ale",
  "Bad Weather Windvane Red",
  "Bell’s Oberon",
  "Big Wood Bad Axe Imperial IPA",
  "Blanche de Bruxelles",
  "Blanche de Bruxelles  Brasserie Lefebvre",
  "Boulder Mojo on Nitro",
  "Boulevard Tank 7 Saison",
  "Brew Dog Rip Tide ",
  "Brooklyn Irish Style Stout",
  "Brooklyn Local #1 ",
  "Brooklyn Local #2 ",
  "Brooklyn Pilsner",
  "Burton Bridge Olde Expensive Ale ",
  "Bøgedal Nr. 0156  ",
  "Chapeau Faro De Troch",
  "Chapeau Framboise De Troch",
  "Chapeau Kriek De Troch",
  "Chimay Grande Réserve – Blue ",
  "Chimay Première – Red",
  "Chimay Tripel – White ",
  "Cisco Cider",
  "Clown Shoes Clementine  ",
  "Clown Shoes Porcine Unidragon",
  "Dark Horse Artic Dekoorc Eert",
  "Dark Horse Crooked Tree IPA",
  "Dark Horse Edacsac Dekoorc Eert",
  "Dark Horse FF Dekoorc Eert",
  "Deschutes Black Butte Porter",
  "Deschutes Jubel  Vintage 2010 ",
  "DeuS",
  "Duvel ",
  "Flying Dog In Heat Wheat",
  "Founders All Day IPA",
  "Founders Centennial IPA",
  "Founders Double Trouble",
  "Fraoch 20th Anniversary Ale Heather Ales",
  "Fuller’s Organic Honey Dew",
  "Fulton Rye Saison",
  "Fulton Sweet Child O’ Vine",
  "Furthermore Full Thicket",
  "Goose Island 312",
  "Goose Island Big John",
  "Goose Island Lolita ",
  "Grand Teton Sweetgrass APA",
  "Grand Teton Wake Up Call 2011",
  "Great Lakes Dortmunder Gold",
  "Greens Discovery Amber",
  "Greens Endeavour Dubbel ",
  "Greens Quest Tripel ",
  "Harriet Sol Bock",
  "Harviestoun ‘Ola Dubh’ 18 year",
  "Harviestoun ‘Ola Dubh’ 30 year",
  "Hinterland Pub Draught Nitro",
  "Hitachino Nest Espresso Stout",
  "Hitachino Nest Extra High XH",
  "Indeed Day Tripper Pale Ale",
  "J.W. Lees Harvest Ale ",
  "Jan De Lichte",
  "Kasteel Rouge",
  "Kwak  ",
  "La Trappe",
  "La Trappe",
  "La Trappe Witte",
  "Lagunitas IPA",
  "Lagunitas PILS",
  "Lake Superior Kayak Kölsch",
  "Left Hand Chainsaw 2008 ",
  "Left Hand Milk Stout",
  "Left Hand Oak-Aged Widdershins Vintage 2007 ",
  "Left Hand Smoked Goosinator 2007",
  "Lindemans Framboise",
  "Lindemans Kriek",
  "Lucid Air",
  "Lucid Foto ",
  "McNeill’s Sunshine IPA",
  "Millstream Imperial Wit IPA",
  "Moylan’s Ryan Sullivan Imperial Stout",
  "New Belgium Hoppy Bock",
  "New Belgium Rampant Imperial IPA",
  "New Belgium Shift",
  "New Holland Dragon’s Milk",
  "New Holland Pilgrims Dole  Vintage 2008",
  "OIvalde The Auroch’s Horn",
  "Odell IPA",
  "Ommegang Bier de Mars ",
  "Ommegang Three Philosophers 2010",
  "Ommegang Three Philosophers 2011",
  "Ommegang  Rare Vos ",
  "Orval Ale ",
  "O’Hara’s Irish Dry Stout on Nitro",
  "Paulaner Premium Pils",
  "Rochefort 10",
  "Rochefort 8",
  "Rodenbach",
  "Rogue Brewer’s Ale 2008 ",
  "Rogue Captain Sig’s Northwestern Ale",
  "Rush River The Unforgiven Amber",
  "Samuel Smith’s Oatmeal Stout",
  "Scaldis Noël Brasserie Dubuisson Frères",
  "Scaldis Prestige  Brasserie Dubuisson Frères",
  "Somersby",
  "Southern Tier Cuvée Series “One” ",
  "Spaten Optimator",
  "St. Feuillien Brune",
  "St. Feuillien Cuvée De Noël",
  "Summit Extra Pale Ale",
  "Summit Sága IPA",
  "Surly Bender",
  "Surly Coffee Bender",
  "Surly Furious",
  "Thomas Hardy’s Ale O’Hanlon’s Brewing",
  "Tripel Karmeliet ",
  "Two Brothers Bare Tree Weiss Wine Vintage 2008",
  "Tyranena Rocky’s Revenge",
  "Unibroue La Terrible",
  "Unibroue Quatre Centiéme",
  "Unibroue Seigneubiale",
  "Warsteiner",
  "Westmalle Dubbel",
  "Westmalle Tripel ",
  "Widmer Hopside Down",
  "Widmer Omission Lager",
  "Widmer Omission Pale ",
  "la Goudale  Les Brasseurs de Gayant"
]

beer_objs = beers.map do |beer_name|
  Beer.create name: beer_name.encode
end

Establishment.all.each do |est|
  beer_objs.shuffle.take(50).each do |beer|
    est.beers << beer
  end
end
